spring:
  application:
    name: helpdesk
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 123456
    url: jdbc:postgresql://localhost:5432/helpdesk
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update

